2023-12-12 22:45:00,288 file.manager INFO 2.0.1
2023-12-12 22:45:00,288 file.manager INFO Copyright (C) 2003-2022, Noriaki Ando and OpenRTM development team,
2023-12-12 22:45:00,288 file.manager INFO   Intelligent Systems Research Institute, AIST,
2023-12-12 22:45:00,288 file.manager INFO Copyright (C) 2022, Noriaki Ando and OpenRTM development team,
2023-12-12 22:45:00,288 file.manager INFO   Industrial Cyber-Physical Research Center, AIST,
2023-12-12 22:45:00,288 file.manager INFO   All right reserved.
2023-12-12 22:45:00,288 file.manager INFO Manager starting.
2023-12-12 22:45:00,288 file.manager INFO Starting local logging.
2023-12-12 22:45:00,303 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2023-12-12 22:45:04,360 file.ManagerServant INFO Master manager not found
2023-12-12 22:45:04,360 file.LocalServiceAdmin INFO All the local services are enabled.
2023-12-12 22:45:04,360 file.manager INFO Component type conf file: sarch_spot.conf loaded.
2023-12-12 22:45:04,360 file.ec_base INFO setRate(1000000.000000) done
2023-12-12 22:45:04,360 file.ec_base INFO setRate(1000.000000) done
2023-12-12 22:45:04,360 file.rtobject INFO 1 execution context was created.
2023-12-12 22:45:04,360 file.rtobject INFO Initial active configuration set is default.
2023-12-12 22:45:18,488 file.ManagerServant INFO Master manager not found
2023-12-12 22:45:28,563 file.ManagerServant INFO Master manager not found
2023-12-12 22:45:38,624 file.ManagerServant INFO Master manager not found
2023-12-12 22:45:48,683 file.ManagerServant INFO Master manager not found
2023-12-12 22:45:58,712 file.ManagerServant INFO Master manager not found
2023-12-12 22:46:08,732 file.ManagerServant INFO Master manager not found
2023-12-12 22:46:09,843 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Users\reore\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenRTM_aist\DataFlowComponentBase.py", line 123, in on_execute
    ret = self.onExecute(ec_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reore\workspace\sarch_spot\sarch_spot.py", line 324, in onExecute
    draw_lines_updated(image_array, center_of_image, 15, specific_color, road_colors, ignore_radius_ratio)
  File "C:\Users\reore\workspace\sarch_spot\sarch_spot.py", line 291, in draw_lines_updated
    self.blue_points.append(x, y)
TypeError: list.append() takes exactly one argument (2 given)

2023-12-12 22:46:15,705 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2023-12-12 22:46:18,827 file.ManagerServant INFO Master manager not found
2023-12-12 22:46:19,555 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2023-12-12 22:46:19,555 file.SdoServiceAdmin ERROR type  not exists.
