2023-12-12 22:28:40,515 file.manager INFO 2.0.1
2023-12-12 22:28:40,515 file.manager INFO Copyright (C) 2003-2022, Noriaki Ando and OpenRTM development team,
2023-12-12 22:28:40,515 file.manager INFO   Intelligent Systems Research Institute, AIST,
2023-12-12 22:28:40,515 file.manager INFO Copyright (C) 2022, Noriaki Ando and OpenRTM development team,
2023-12-12 22:28:40,515 file.manager INFO   Industrial Cyber-Physical Research Center, AIST,
2023-12-12 22:28:40,515 file.manager INFO   All right reserved.
2023-12-12 22:28:40,515 file.manager INFO Manager starting.
2023-12-12 22:28:40,515 file.manager INFO Starting local logging.
2023-12-12 22:28:40,530 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2023-12-12 22:28:44,584 file.ManagerServant INFO Master manager not found
2023-12-12 22:28:44,584 file.LocalServiceAdmin INFO All the local services are enabled.
2023-12-12 22:28:44,591 file.manager INFO Component type conf file: sarch_spot.conf loaded.
2023-12-12 22:28:44,591 file.ec_base INFO setRate(1000000.000000) done
2023-12-12 22:28:44,591 file.ec_base INFO setRate(1000.000000) done
2023-12-12 22:28:44,591 file.rtobject INFO 1 execution context was created.
2023-12-12 22:28:44,591 file.rtobject INFO Initial active configuration set is default.
2023-12-12 22:28:58,705 file.ManagerServant INFO Master manager not found
2023-12-12 22:29:08,741 file.ManagerServant INFO Master manager not found
2023-12-12 22:29:18,776 file.ManagerServant INFO Master manager not found
2023-12-12 22:29:28,849 file.ManagerServant INFO Master manager not found
2023-12-12 22:29:38,879 file.ManagerServant INFO Master manager not found
2023-12-12 22:29:48,781 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Users\reore\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenRTM_aist\DataFlowComponentBase.py", line 123, in on_execute
    ret = self.onExecute(ec_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reore\workspace\sarch_spot\sarch_spot.py", line 324, in onExecute
    draw_lines_updated(image_array, center_of_image, 15, specific_color, road_colors, ignore_radius_ratio)
  File "C:\Users\reore\workspace\sarch_spot\sarch_spot.py", line 291, in draw_lines_updated
    blue_points.append((x, y))
    ^^^^^^^^^^^
NameError: name 'blue_points' is not defined

2023-12-12 22:29:48,934 file.ManagerServant INFO Master manager not found
2023-12-12 22:29:58,981 file.ManagerServant INFO Master manager not found
2023-12-12 22:30:05,299 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2023-12-12 22:30:07,128 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2023-12-12 22:30:07,128 file.SdoServiceAdmin ERROR type  not exists.
2023-12-12 22:30:09,004 file.ManagerServant INFO Master manager not found
